variable "enabled_policy_map" {
  description = "Enter the list of services that you would like to Enable"
  type        = map(string)
  default = {
    azure-aks                 = "aksEnabled"
    azure-apimanagement       = "apiManagementEnabled"
    azure-applicationgateway  = "applicationGatewayServiceEnabled"
    azure-applicationinsights = "applicationInsightsEnabled"
    azure-appservice          = "appServiceEnabled"
    azure-automation          = "automationEnabled"
    azure-compute             = "computeEnabled"
    azure-cosmosdb            = "cosmosDbEnabled"
    azure-databricks          = "databricksEnabled"
    azure-datafactory         = "dataFactoryEnabled"
    azure-dns                 = "dnsEnabled"
    azure-firewall            = "firewallServiceEnabled"
    azure-frontdoorservice    = "frontDoorServiceEnabled"
    azure-iam                 = "iamEnabled"
    azure-keyvault            = "keyVaultEnabled"
    azure-loadbalancer        = "loadBalancerServiceEnabled"
    azure-loganalytics        = "logAnalyticsEnabled"
    azure-monitor             = "monitorEnabled"
    azure-mysql               = "mySqlEnabled"
    azure-network             = "networkEnabled"
    azure-networkwatcher      = "networkWatcherServiceEnabled"
    azure-postgresql          = "postgreSqlEnabled"
    azure-recoveryservice     = "recoveryServiceEnabled"
    azure-relay               = "relayEnabled"
    azure-searchmanagement    = "searchManagementEnabled"
    azure-securitycenter      = "securityCenterServiceEnabled"
    azure-servicebus          = "serviceBusEnabled"
    azure-signalr             = "signalRServiceEnabled"
    azure-sql                 = "sqlEnabled"
    azure-sqlvirtualmachine   = "sqlVirtualMachineServiceEnabled"
    azure-storage             = "storageEnabled"
    azure-synapseanalytics    = "synapseAnalyticsEnabled"
  }
}

variable "provider_status" {
  description = <<-EOF
    Choose the subset of providers that should be configured.
    Possible values for each service are: 
      - "Skip"
      - "Check: Not Registered"
      - "Check: Registered"
      - "Enforce: Not Registered"
      - "Enforce: Registered"
    EOF
  type        = map(string)
  default = {
    ApiManagement       = "Enforce: Registered"
    Automation          = "Enforce: Registered"
    Billing             = "Enforce: Registered"
    Compute             = "Enforce: Registered"
    ContainerService    = "Enforce: Registered"
    CostManagement      = "Enforce: Registered"
    DBforMySQL          = "Enforce: Registered"
    DBforPostgreSQL     = "Enforce: Registered"
    DataFactory         = "Enforce: Registered"
    DataLakeAnalytics   = "Enforce: Registered"
    Databricks          = "Enforce: Registered"
    DocumentDB          = "Enforce: Registered"
    DomainRegistration  = "Enforce: Registered"
    HDInsight           = "Enforce: Registered"
    Insights            = "Enforce: Registered"
    KeyVault            = "Enforce: Registered"
    Network             = "Enforce: Registered"
    OperationalInsights = "Enforce: Registered"
    RecoveryServices    = "Enforce: Registered"
    Relay               = "Enforce: Registered"
    Resources           = "Enforce: Registered"
    Search              = "Enforce: Registered"
    Security            = "Enforce: Registered"
    ServiceBus          = "Enforce: Registered"
    SignalRService      = "Enforce: Registered"
    Sql                 = "Enforce: Registered"
    SqlVirtualMachine   = "Enforce: Registered"
    Storage             = "Enforce: Registered"
    Synapse             = "Enforce: Registered"
    Web                 = "Enforce: Registered"
  }
}

variable "provider_registration_map" {
  description = "A map of all the registered policies currently exposed by Turbot"
  type        = map(string)
  default = {
    ApiManagement       = "apiManagementRegistered"
    Automation          = "automationRegistered"
    Billing             = "billingRegistered"
    Compute             = "computeRegistered"
    ContainerService    = "containerServiceRegistered"
    CostManagement      = "costManagementRegistered"
    DBforMySQL          = "dbforMySqlRegistered"
    DBforPostgreSQL     = "dbForPostgreSqlRegistered"
    DataFactory         = "dataFactoryRegistered"
    DataLakeAnalytics   = "dataLakeAnalyticsRegistered"
    Databricks          = "databricksRegistered"
    DocumentDB          = "documentDbRegistered"
    DomainRegistration  = "domainRegistrationRegistered"
    HDInsight           = "hdInsightRegistered"
    Insights            = "insightsRegistered"
    KeyVault            = "keyVaultRegistered"
    Network             = "networkRegistered"
    OperationalInsights = "operationalInsightsRegistered"
    RecoveryServices    = "recoveryServicesRegistered"
    Relay               = "relayRegistered"
    Resources           = "resourcesRegistered"
    Search              = "searchRegistered"
    Security            = "securityRegistered"
    ServiceBus          = "serviceBusRegistered"
    SignalRService      = "signalRServiceRegistered"
    Sql                 = "sqlRegistered"
    SqlVirtualMachine   = "sqlVirtualMachineRegistered"
    Storage             = "storageRegistered"
    Synapse             = "synapseRegistered"
    Web                 = "webRegistered"
  }
}
