## GraphQL query to retrieve notifications of type 'resource_deleted' for AWS EC2 snapshot resources, with pagination support.

query Notifications($filter: [String!], $paging: String, $dataSource: NotificationDataSource) {
  notifications(filter: $filter, paging: $paging, dataSource: $dataSource) {
    items {
      ...notification
      data
      __typename
    }
    paging {
      next
      __typename
    }
    metadata {
      stats {
        total
        __typename
      }
      __typename
    }
    __typename
  }
}

fragment notification on Notification {
  ...notificationFields
  control {
    ...controlNotification
    __typename
  }
  oldControl {
    ...controlNotification
    __typename
  }
  grant {
    ...grantNotification
    __typename
  }
  oldGrant {
    ...grantNotification
    __typename
  }
  activeGrant {
    ...activeGrantNotification
    __typename
  }
  oldActiveGrant {
    ...activeGrantNotification
    __typename
  }
  policySetting {
    ...policySettingNotification
    __typename
  }
  oldPolicySetting {
    ...policySettingNotification
    __typename
  }
  policyValue {
    ...policyValueNotification
    __typename
  }
  oldPolicyValue {
    ...policyValueNotification
    __typename
  }
  resource {
    ...resourceNotification
    __typename
  }
  oldResource {
    ...resourceNotification
    __typename
  }
  actor {
    ...actorNotification
    __typename
  }
  turbot {
    ...notificationMetadataFields
    __typename
  }
  __typename
}

fragment activeGrantNotification on ActiveGrant {
  grant {
    ...grantNotification
    __typename
  }
  turbot {
    ...activeGrantMetadataFields
    __typename
  }
  __typename
}

fragment activeGrantMetadataFields on TurbotActiveGrantMetadata {
  id
  versionId
  createTimestamp
  __typename
}

fragment grantMetadataFields on TurbotGrantMetadata {
  id
  versionId
  createTimestamp
  __typename
}

fragment permissionMetadataFields on TurbotPermissionMetadata {
  id
  path
  title
  __typename
}

fragment trunkFields on TrunkItems {
  title
  items {
    ...trunkItemFields
    __typename
  }
  __typename
}

fragment trunkItemFields on TrunkItem {
  turbot {
    id
    path
    title
    __typename
  }
  __typename
}

fragment actorNotification on Actor {
  identity {
    ...identityFields
    __typename
  }
  persona {
    ...identityFields
    __typename
  }
  role {
    ...identityFields
    __typename
  }
  alternatePersona
  __typename
}

fragment identityFields on Identity {
  picture
  title
  type {
    uri
    turbot {
      ...resourceTypeMetadataFields
      __typename
    }
    __typename
  }
  turbot {
    ...resourceMetadataFields
    __typename
  }
  __typename
}

fragment resourceMetadataFields on TurbotResourceMetadata {
  akas
  id
  parentId
  path
  title
  versionId
  __typename
}

fragment controlNotification on Control {
  state
  type {
    icon
    trunk {
      ...trunkFields
      __typename
    }
    turbot {
      ...controlTypeMetadataFields
      __typename
    }
    __typename
  }
  turbot {
    ...controlMetadataFields
    __typename
  }
  __typename
}

fragment controlMetadataFields on TurbotControlMetadata {
  id
  stateChangeTimestamp
  versionId
  __typename
}

fragment controlTypeMetadataFields on TurbotControlTypeMetadata {
  id
  title
  __typename
}

fragment grantNotification on Grant {
  roleName
  groupName
  type {
    trunk {
      ...trunkFields
      __typename
    }
    turbot {
      ...permissionMetadataFields
      __typename
    }
    __typename
  }
  level {
    turbot {
      ...permissionMetadataFields
      __typename
    }
    __typename
  }
  identity {
    turbot {
      ...resourceMetadataFields
      __typename
    }
    __typename
  }
  turbot {
    ...grantMetadataFields
    __typename
  }
  __typename
}

fragment notificationFields on Notification {
  notificationType
  icon
  message
  __typename
}

fragment notificationMetadataFields on TurbotNotificationMetadata {
  updateTimestamp
  createTimestamp
  id
  processId
  __typename
}

fragment policySettingNotification on PolicySetting {
  default
  isCalculated
  orphan
  exception
  precedence
  template
  templateInput
  value
  valueSource
  note
  validToTimestamp
  resource {
    turbot {
      ...resourceMetadataFields
      __typename
    }
    __typename
  }
  type {
    icon
    trunk {
      ...trunkFields
      __typename
    }
    turbot {
      ...policyTypeMetadataFields
      __typename
    }
    __typename
  }
  turbot {
    ...policySettingMetadataFields
    __typename
  }
  __typename
}

fragment policySettingMetadataFields on TurbotPolicySettingMetadata {
  id
  timestamp
  createTimestamp
  updateTimestamp
  versionId
  __typename
}

fragment policyTypeMetadataFields on TurbotPolicyTypeMetadata {
  id
  title
  parentId
  __typename
}

fragment policyValueNotification on PolicyValue {
  default
  value
  isCalculated
  state
  reason
  precedence
  lastProcess {
    turbot {
      id
      __typename
    }
    __typename
  }
  setting {
    resource {
      turbot {
        ...resourceMetadataFields
        __typename
      }
      __typename
    }
    turbot {
      ...policySettingMetadataFields
      __typename
    }
    __typename
  }
  type {
    ...policyTypeFields
    trunk {
      ...trunkFields
      __typename
    }
    turbot {
      ...policyTypeMetadataFields
      __typename
    }
    __typename
  }
  turbot {
    ...policyValueMetadataFields
    __typename
  }
  __typename
}

fragment policyTypeFields on PolicyType {
  class
  defaultTemplate
  defaultTemplateInput
  description
  icon
  readOnly
  resolvedSchema
  secret
  secretLevel
  targets
  uri
  __typename
}

fragment policyValueMetadataFields on TurbotPolicyValueMetadata {
  id
  settingId
  nextTickTimestamp
  stateChangeTimestamp
  createTimestamp
  versionId
  __typename
}

fragment resourceNotification on Resource {
  trunk {
    ...trunkFields
    __typename
  }
  type {
    ...resourceTypeFields
    trunk {
      ...trunkFields
      __typename
    }
    turbot {
      ...resourceTypeMetadataFields
      __typename
    }
    __typename
  }
  turbot {
    ...resourceMetadataFields
    __typename
  }
  object
  __typename
}

fragment resourceTypeFields on ResourceType {
  description
  icon
  uri
  __typename
}

fragment resourceTypeMetadataFields on TurbotResourceTypeMetadata {
  id
  path
  title
  __typename
}


## Variables for the GraphQL query, specifying the filter for 'resource_deleted' notifications related to AWS EC2 snapshot resources, and pagination settings.

{
  "filter": [
    "notificationType:resource_deleted  resourceTypeId:'tmod:@turbot/aws-ec2#/resource/types/snapshot'",
    "limit:300"
  ],
  "paging": "YOUR_PAGING_CURSOR_HERE"
}

## Variables for the GraphQL query, specifying the filter for 'resource_deleted' notifications related to AWS EC2 snapshot resources by a specific actor, and pagination settings.


  "filter": [
    "notificationType:resource_deleted actorIdentityId:YOUR_ACTOR_IDENTITY_ID resourceTypeId:'tmod:@turbot/aws-ec2#/resource/types/snapshot'",
    "limit:300"
  ],
  "paging": "YOUR_PAGING_CURSOR_HERE"
}

## Variables for the GraphQL query to fetch notifications for snapshot deletions by a specific actor, without pagination settings.

{
  "filter":"notificationType:resource_deleted actorIdentityId:YOUR_ACTOR_IDENTITY_ID resourceTypeId:'tmod:@turbot/aws-ec2#/resource/types/snapshot'"
}