#!/usr/bin/env python3
"""
Complete solution: Discover installed mods and generate YAML config
that Terraform can consume dynamically.

Usage:
    ./discover_and_generate.py <workspace> > policies.yaml
    terraform apply
"""

import subprocess
import json
import sys
from datetime import datetime

def query_graphql(workspace, query):
    """Execute GraphQL query against workspace."""
    result = subprocess.run(
        ["turbot", "graphql", workspace, "--query", query],
        capture_output=True,
        text=True
    )
    
    if result.returncode != 0:
        print(f"Error: {result.stderr}", file=sys.stderr)
        sys.exit(1)
    
    return json.loads(result.stdout)

def get_cmdb_policy_types(workspace):
    """Get all CMDB policy types from installed mods."""
    query = """
    {
      policyTypes(filter: "title:CMDB modType:aws") {
        items {
          uri
          title
          mod {
            uri
            title
          }
          parent {
            trunk {
              title
            }
          }
        }
      }
    }
    """
    
    data = query_graphql(workspace, query)
    
    # Categorize policies
    critical_keywords = ["Account", "Region", "Organization", "Event Handler"]
    prevention_keywords = ["Service Control Policy", "Resource Control Policy"]
    
    categories = {
        "event_handlers": {},
        "prevention_cmdb": {},
        "service_cmdb_skip": {}
    }
    
    for policy in data["policyTypes"]["items"]:
        resource_path = " > ".join([t["title"] for t in policy["parent"]["trunk"]])
        uri = policy["uri"]
        
        # Skip critical infrastructure
        if any(keyword in resource_path for keyword in critical_keywords):
            continue
        
        # Categorize prevention-related
        if any(keyword in resource_path for keyword in prevention_keywords):
            key = uri.split("/")[-1].replace("Cmdb", "").lower()
            categories["prevention_cmdb"][key] = {
                "type": uri,
                "value": "Enforce: Enabled",
                "note": f"{resource_path}"
            }
        else:
            # Service resources
            key = uri.split("/")[-1].replace("Cmdb", "").lower()
            categories["service_cmdb_skip"][key] = {
                "type": uri,
                "note": f"{resource_path}"
            }
    
    # Add event handlers explicitly
    categories["event_handlers"] = {
        "regional": {
            "type": "tmod:@turbot/aws#/policy/types/eventHandlers",
            "value": "Enforce: Configured",
            "note": "REQUIRED for real-time event processing"
        },
        "global": {
            "type": "tmod:@turbot/aws#/policy/types/eventHandlersGlobal",
            "value": "Enforce: Configured",
            "note": "REQUIRED for global event routing"
        }
    }
    
    return categories

def generate_yaml(workspace, categories):
    """Generate YAML configuration."""
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    
    yaml = f"""# =============================================================================
# Auto-Generated CMDB Policy Configuration
# =============================================================================
# Workspace: {workspace}
# Generated: {timestamp}
#
# This file was auto-generated by discover_and_generate.py
# It reflects the actual installed mods in the workspace
# =============================================================================

# Critical infrastructure (always enabled)
event_handlers:
"""
    
    for key, value in categories["event_handlers"].items():
        yaml += f"""  {key}:
    type: "{value['type']}"
    value: "{value['value']}"
    note: "{value['note']}"
"""
    
    yaml += """
# Prevention discovery (enabled)
prevention_cmdb:
"""
    
    for key, value in categories["prevention_cmdb"].items():
        yaml += f"""  {key}:
    type: "{value['type']}"
    value: "{value['value']}"
    note: "{value['note']}"
"""
    
    yaml += """
# Service resource CMDB (disabled for cost)
service_cmdb_skip:
"""
    
    for key, value in categories["service_cmdb_skip"].items():
        yaml += f"""  {key}:
    type: "{value['type']}"
    note: "{value['note']}"
"""
    
    return yaml

def main():
    if len(sys.argv) != 2:
        print("Usage: discover_and_generate.py <workspace>", file=sys.stderr)
        print("Example: discover_and_generate.py procare-production.turbot.com > policies.yaml", file=sys.stderr)
        sys.exit(1)
    
    workspace = sys.argv[1]
    
    print(f"# Discovering CMDB policies in {workspace}...", file=sys.stderr)
    categories = get_cmdb_policy_types(workspace)
    
    prevention_count = len(categories["prevention_cmdb"])
    service_count = len(categories["service_cmdb_skip"])
    print(f"# Found {prevention_count} prevention policies, {service_count} service policies", file=sys.stderr)
    print(f"# Generating YAML...", file=sys.stderr)
    
    yaml = generate_yaml(workspace, categories)
    print(yaml)
    
    print(f"", file=sys.stderr)
    print(f"# Next steps:", file=sys.stderr)
    print(f"#   1. Review the generated policies.yaml", file=sys.stderr)
    print(f"#   2. Customize if needed (add/remove entries)", file=sys.stderr)
    print(f"#   3. Run: terraform init && terraform plan", file=sys.stderr)
    print(f"#   4. Run: terraform apply", file=sys.stderr)

if __name__ == "__main__":
    main()
