variable "mod_list" {
  type        = list(string)
  description = "The list of Azure Mods to install."
  default = [
    "azure",
    "azure-activedirectory",
    "azure-aks",
    "azure-apimanagement",
    "azure-applicationgateway",
    "azure-applicationinsights",
    "azure-appservice",
    "azure-automation",
    "azure-cisv1",
    "azure-cisv1-2",
    "azure-cisv2-0",
    "azure-compute",
    "azure-cosmosdb",
    "azure-databricks",
    "azure-datafactory",
    "azure-dns",
    "azure-firewall",
    "azure-frontdoorservice",
    "azure-iam",
    "azure-keyvault",
    "azure-loadbalancer",
    "azure-loganalytics",
    "azure-monitor",
    "azure-mysql",
    "azure-network",
    "azure-networkwatcher",
    "azure-postgresql",
    "azure-provider",
    "azure-recoveryservice",
    "azure-relay",
    "azure-searchmanagement",
    "azure-securitycenter",
    "azure-servicebus",
    "azure-signalr",
    "azure-sql",
    "azure-sqlvirtualmachine",
    "azure-storage",
    "azure-synapseanalytics"
  ]
}
