mod_list = [
    "aws",
    "aws-cisv1",
    "aws-cloudtrail",
    "aws-cloudwatch",
    "aws-config",
    "aws-ec2",
    "aws-events",
    "aws-iam",
    "aws-kms",
    "aws-lambda",
    "aws-logs",
    "aws-s3",
    "aws-sns",
    "aws-vpc-core",
    "aws-vpc-connect",
    "aws-vpc-internet",
    "aws-vpc-security"
]