
locals {
  policy_map = {
    gcp-appengine        = "appEngineEnabled"
    gcp-bigquery         = "bigQueryEnabled"
    gcp-bigtable         = "bigtableEnabled"
    gcp-build            = "buildServiceEnabled"
    gcp-composer         = "composerEnabled"
    gcp-computeengine    = "computeEngineEnabled"
    gcp-datacatalog      = "dataCatalogEnabled"
    gcp-dataflow         = "dataflowEnabled"
    gcp-dataproc         = "dataprocEnabled"
    gcp-dns              = "dnsEnabled"
    gcp-functions        = "functionsEnabled"
    gcp-iam              = "iamEnabled"
    gcp-kms              = "kmsEnabled"
    gcp-kubernetesengine = "kubernetesEngineEnabled"
    gcp-logging          = "loggingEnabled"
    gcp-memorystore      = "memorystoreEnabled"
    gcp-monitoring       = "monitoringEnabled"
    gcp-network          = "networkServiceEnabled"
    gcp-notebooks        = "notebooksEnabled"
    gcp-pubsub           = "pubsubEnabled"
    gcp-scheduler        = "schedulerEnabled"
    gcp-spanner          = "spannerEnabled"
    gcp-sql              = "sqlEnabled"
    gcp-storage          = "storageEnabled"
    ##gcp-orgpolicy        = ""  ## Note: OrgPolicy does not have an Enabled
  }

  api_policy_map = {
    gcp-appengine        = "appEngineApiEnabled"
    gcp-bigquery         = "bigQueryApiEnabled"
    gcp-bigtable         = "bigtableApiEnabled"
    gcp-build            = "buildServiceApiEnabled"
    gcp-composer         = "composerApiEnabled"
    gcp-computeengine    = "computeEngineApiEnabled"
    gcp-datacatalog      = "dataCatalogApiEnabled"
    gcp-dataflow         = "dataflowApiEnabled"
    gcp-dataproc         = "dataprocApiEnabled"
    gcp-dns              = "dnsApiEnabled"
    gcp-functions        = "functionsApiEnabled"
    gcp-iam              = "iamApiEnabled"
    gcp-kms              = "kmsApiEnabled"
    gcp-kubernetesengine = "kubernetesEngineApiEnabled"
    gcp-logging          = "loggingApiEnabled"
    gcp-memorystore      = "memorystoreApiEnabled"
    gcp-monitoring       = "monitoringApiEnabled"
    gcp-network          = "networkServiceApiEnabled"
    gcp-notebooks        = "notebooksApiEnabled"
    gcp-pubsub           = "pubsubApiEnabled"
    gcp-scheduler        = "schedulerApiEnabled"
    gcp-spanner          = "spannerApiEnabled"
    gcp-sql              = "sqlApiEnabled"
    gcp-storage          = "storageApiEnabled"
    ##gcp-orgpolicy        = ""  ## Note: OrgPolicy does not have an API Enabled
  }
}
