# See file, applicationgateway_policies.tf
enable_application_gateway_approved_policies = true

# See file, applicationgateway_policies.tf
enable_network_security_group_ingress_rules_approved_policies = true
enable_network_security_group_ingress_rules_approved_rules_policies = true
enable_network_public_ip_address_approved_usage_policies = true

# See file, storage_policies.tf
enable_storage_account_public_access_policies = true
enable_azure_storage_container_public_access_policies = true

