mod_list = [
  "azure",
  "azure-iam",
  "azure-provider",
  "azure-aks",
  "azure-appservice",
  "azure-compute",
  "azure-keyvault",
  "azure-monitor",
  "azure-mysql",
  "azure-network",
  "azure-networkwatcher",
  "azure-postgresql",
  "azure-securitycenter",
  "azure-sql",
  "azure-storage",
  "azure-cisv1",
  "cis"
]
