locals {
## Mapping of resource name to resource tag policy
# Note: the resource map above dictates the applicable use of each line item below.  You do not need to comment out these items to reduce scope
policy_map  = {
    gcp-bigtable-cluster                  : "tmod:@turbot/gcp-bigtable#/policy/types/clusterApproved"
    gcp-composer-environment              : "tmod:@turbot/gcp-composer#/policy/types/environmentApproved"
    gcp-computeengine-disk                : "tmod:@turbot/gcp-computeengine#/policy/types/diskApproved"
    gcp-computeengine-instance            : "tmod:@turbot/gcp-computeengine#/policy/types/instanceApproved"
    gcp-computeengine-node-group          : "tmod:@turbot/gcp-computeengine#/policy/types/nodeGroupApproved"
    gcp-computeengine-node-template       : "tmod:@turbot/gcp-computeengine#/policy/types/nodeTemplateApproved"
    gcp-computeengine-region-disk         : "tmod:@turbot/gcp-computeengine#/policy/types/regionDiskApproved"
    gcp-computeengine-region-health-check : "tmod:@turbot/gcp-computeengine#/policy/types/regionHealthCheckApproved"
    gcp-dataflow-job                      : "tmod:@turbot/gcp-dataflow#/policy/types/jobApproved"
    gcp-dataproc-cluster                  : "tmod:@turbot/gcp-dataproc#/policy/types/clusterApproved"
    gcp-dataproc-job                      : "tmod:@turbot/gcp-dataproc#/policy/types/jobApproved"
    gcp-dataproc-workflowtemplate         : "tmod:@turbot/gcp-dataproc#/policy/types/workflowTemplateApproved"
    gcp-functions-function                : "tmod:@turbot/gcp-functions#/policy/types/functionApproved"
    gcp-kms-cryptokey                     : "tmod:@turbot/gcp-kms#/policy/types/cryptoKeyApproved"
    gcp-kubernetesengine-region-cluster   : "tmod:@turbot/gcp-kubernetesengine#/policy/types/regionClusterApproved"
    gcp-kubernetesengine-region-node-pool : "tmod:@turbot/gcp-kubernetesengine#/policy/types/regionNodePoolApproved"
    gcp-kubernetesengine-zone-cluster     : "tmod:@turbot/gcp-kubernetesengine#/policy/types/zoneClusterApproved"
    gcp-kubernetesengine-zone-node-pool   : "tmod:@turbot/gcp-kubernetesengine#/policy/types/zoneNodePoolApproved"
    gcp-network-address                   : "tmod:@turbot/gcp-network#/policy/types/addressApproved"
    gcp-network-forwarding-rule           : "tmod:@turbot/gcp-network#/policy/types/forwardingRuleApproved"
    gcp-network-region-backend-service    : "tmod:@turbot/gcp-network#/policy/types/regionBackendServiceApproved"
    gcp-network-region-url-map            : "tmod:@turbot/gcp-network#/policy/types/regionUrlMapApproved"
    gcp-network-router                    : "tmod:@turbot/gcp-network#/policy/types/routerApproved"
    gcp-network-subnetwork                : "tmod:@turbot/gcp-network#/policy/types/subnetworkApproved"
    gcp-network-target-pool               : "tmod:@turbot/gcp-network#/policy/types/targetPoolApproved"
    gcp-network-target-vpn-gateway        : "tmod:@turbot/gcp-network#/policy/types/targetVpnGatewayApproved"
    gcp-network-vpn-tunnel                : "tmod:@turbot/gcp-network#/policy/types/vpnTunnelApproved"
    gcp-scheduler-job                     : "tmod:@turbot/gcp-scheduler#/policy/types/jobApproved"
    gcp-spanner-instance                  : "tmod:@turbot/gcp-spanner#/policy/types/instanceApproved"
    gcp-sql-backup                        : "tmod:@turbot/gcp-sql#/policy/types/backupApproved"
    gcp-sql-database                      : "tmod:@turbot/gcp-sql#/policy/types/databaseApproved"
    gcp-sql-instance                      : "tmod:@turbot/gcp-sql#/policy/types/instanceApproved"
    gcp-storage-bucket                    : "tmod:@turbot/gcp-storage#/policy/types/bucketApproved"
    gcp-storage-object                    : "tmod:@turbot/gcp-storage#/policy/types/objectApproved"
  }
}